services:
  - type: web
    name: cecar-asesorias
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:aplicacion
    envVars:
      - key: MAKE_WEBHOOK_URL
        value: ""
